export const Types = {
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  REMOVE_AUTH_TOKEN: 'REMOVE_AUTH_TOKEN',
  SET_USER_ROLE: 'SET_USER_ROLE',
  SET_CATALOG: 'SET_CATALOG',
  ADD_TO_CART: 'ADD_TO_CART',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
};
